version: '3.1'

services:
  db:
    container_name: db
    image: wachira90/postgres:10.15
    restart: always
    environment:
      POSTGRES_PASSWORD: zxczxc
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb

  gfa:
    container_name: gfa
    image: wachira90/grafana:7.3.6
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

  adminer:
    container_name: adminer
    image: wachira90/adminer:4.7.8
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
